import { AppNotification } from '../models';
import { addMonthKey, currentMonthKey, formatMonth, toIsoDate } from '../shared/utils/date.util';

function minutesAgo(minutes: number): string {
  const d = new Date(Date.now() - minutes * 60_000);
  const hh = String(d.getHours()).padStart(2, '0');
  const mm = String(d.getMinutes()).padStart(2, '0');
  return `${toIsoDate(d)}T${hh}:${mm}:00`;
}

const lastMonth = formatMonth(addMonthKey(currentMonthKey(), -1), true);

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: 'NT-01',
    type: 'fee_received',
    title: 'Fee received — ₹21,000',
    message: 'Aparna Menon (Full Stack Development) paid installment 3 via UPI.',
    at: minutesAgo(12),
    read: false,
    audience: ['Admin', 'Advisor'],
    link: '/fees/payments',
  },
  {
    id: 'NT-02',
    type: 'leave_request',
    title: 'Leave request from Muhammed Shafi',
    message: '2 days of casual leave requested. Awaiting your approval.',
    at: minutesAgo(46),
    read: false,
    audience: ['Admin'],
    link: '/hr/leave',
  },
  {
    id: 'NT-03',
    type: 'follow_up_due',
    title: 'Follow-ups due today',
    message: 'You have follow-ups scheduled for today. Start with the earliest one.',
    at: minutesAgo(70),
    read: false,
    audience: ['Advisor', 'Sales'],
    link: '/admissions/follow-ups',
  },
  {
    id: 'NT-04',
    type: 'attendance_alert',
    title: 'Low attendance alert',
    message: '4 students in Python Development are below 75% attendance this month.',
    at: minutesAgo(125),
    read: false,
    audience: ['Admin', 'Mentor'],
    link: '/attendance/register',
  },
  {
    id: 'NT-05',
    type: 'new_admission',
    title: 'New admission confirmed',
    message: 'Gayathri Nair joined Data Science. Fee plan: 4 installments.',
    at: minutesAgo(190),
    read: false,
    audience: ['Admin', 'Advisor'],
    link: '/admissions/admissions',
  },
  {
    id: 'NT-06',
    type: 'fee_due',
    title: 'Installments due this week',
    message: 'Several installments are due in the next 7 days. Send reminders to avoid late fees.',
    at: minutesAgo(310),
    read: true,
    audience: ['Admin', 'Advisor'],
    link: '/fees/dues',
  },
  {
    id: 'NT-07',
    type: 'follow_up_overdue',
    title: 'Overdue follow-ups',
    message: 'Some follow-ups are overdue by more than 2 days. Reschedule or close them.',
    at: minutesAgo(1180),
    read: false,
    audience: ['Advisor', 'Sales', 'Admin'],
    link: '/admissions/follow-ups',
  },
  {
    id: 'NT-08',
    type: 'system',
    title: 'Biometric device integration',
    message:
      'Device sync is planned for a future release. Attendance is currently marked manually.',
    at: minutesAgo(1500),
    read: true,
    audience: ['Admin'],
    link: '/attendance/staff',
  },
  {
    id: 'NT-09',
    type: 'attendance_alert',
    title: 'Weekly mentor reports pending',
    message: 'Reports for last week are pending for some batches. Please submit them by Monday.',
    at: minutesAgo(1620),
    read: false,
    audience: ['Admin', 'Mentor'],
    link: '/mentor-reports',
  },
  {
    id: 'NT-10',
    type: 'new_admission',
    title: 'Lead converted to admission',
    message: 'One of your leads has been converted to an admission. Great work!',
    at: minutesAgo(1700),
    read: true,
    audience: ['Sales'],
    link: '/admissions/leads',
  },
  {
    id: 'NT-11',
    type: 'leave_request',
    title: 'Leave request submitted',
    message: 'Your earned leave request has been sent to HR for approval.',
    at: minutesAgo(380),
    read: true,
    audience: ['Mentor'],
    link: '/me/leave',
  },
  {
    id: 'NT-12',
    type: 'system',
    title: `Payroll for ${lastMonth} processed`,
    message: 'Payslips are now available under My Payslips.',
    at: minutesAgo(4200),
    read: true,
    audience: ['Admin', 'Advisor', 'Mentor', 'Sales'],
    link: '/me/payslips',
  },
  {
    id: 'NT-13',
    type: 'system',
    title: 'Academic calendar updated',
    message: 'Holiday list for the current academic year has been published.',
    at: minutesAgo(5900),
    read: true,
    audience: ['Admin', 'Advisor', 'Mentor', 'Sales', 'Student'],
    link: null,
  },
  {
    id: 'NT-14',
    type: 'fee_due',
    title: 'Next installment due soon',
    message: 'Your next installment is due in a few days. Pay at the front desk or via UPI.',
    at: minutesAgo(140),
    read: false,
    audience: ['Student'],
    link: '/portal/fees',
  },
  {
    id: 'NT-15',
    type: 'system',
    title: 'New mentor report published',
    message: 'Arjun Krishnan added your weekly progress report.',
    at: minutesAgo(2900),
    read: false,
    audience: ['Student'],
    link: '/portal/reports',
  },
  {
    id: 'NT-16',
    type: 'attendance_alert',
    title: 'Attendance summary',
    message: 'Your attendance this month is above 85%. Keep it up!',
    at: minutesAgo(7300),
    read: true,
    audience: ['Student'],
    link: '/portal/attendance',
  },
  {
    id: 'NT-17',
    type: 'fee_received',
    title: 'Payment recorded by Anjali Nair',
    message: 'Cash payment of ₹15,000 recorded for Rohit Thomas.',
    at: minutesAgo(820),
    read: true,
    audience: ['Admin'],
    link: '/fees/payments',
  },
  {
    id: 'NT-18',
    type: 'follow_up_due',
    title: 'Demo class reminder',
    message: 'Full Stack demo class tomorrow at 11:00 AM — 6 prospects confirmed.',
    at: minutesAgo(560),
    read: false,
    audience: ['Sales', 'Advisor'],
    link: '/admissions/enquiries',
  },
];
