import { AppSettings, PermissionLevel, Role } from '../models';

type Levels = [PermissionLevel, PermissionLevel, PermissionLevel, PermissionLevel, PermissionLevel];

const row = (module: string, [admin, advisor, mentor, sales, student]: Levels) => ({
  module,
  levels: {
    Admin: admin,
    Advisor: advisor,
    Mentor: mentor,
    Sales: sales,
    Student: student,
  } as Record<Role, PermissionLevel>,
});

const year = new Date().getMonth() >= 5 ? new Date().getFullYear() : new Date().getFullYear() - 1;

export const SETTINGS: AppSettings = {
  institute: {
    name: 'Trycod Tech School',
    legalName: 'Trycod Tech School',
    tagline: 'Industry-led software training',
    email: 'hello@trycod-demo.com',
    phone: '+91 484 400 2150',
    website: 'www.trycod-demo.com',
    address: '2nd Floor, Techno Plaza, Seaport–Airport Road',
    city: 'Kakkanad, Kochi',
    state: 'Kerala',
    pincode: '682030',
    gstin: '32ABCDE1234F1Z5',
  },
  academicYear: {
    label: `${year}–${String(year + 1).slice(2)}`,
    startDate: `${year}-06-01`,
    endDate: `${year + 1}-05-31`,
    weeklyOff: 'Sunday',
    holidays: [
      { date: `${year}-08-15`, name: 'Independence Day' },
      { date: `${year}-08-26`, name: 'First Onam' },
      { date: `${year}-08-27`, name: 'Thiruvonam' },
      { date: `${year}-10-02`, name: 'Gandhi Jayanti' },
      { date: `${year}-11-01`, name: 'Kerala Piravi' },
      { date: `${year}-12-25`, name: 'Christmas' },
      { date: `${year + 1}-01-26`, name: 'Republic Day' },
      { date: `${year + 1}-04-14`, name: 'Vishu' },
    ],
  },
  fees: {
    allowInstallments: true,
    maxInstallments: 4,
    minDownPaymentPct: 30,
    installmentGapDays: 30,
    lateFeeType: 'Flat',
    lateFeeValue: 500,
    graceDays: 5,
    receiptPrefix: 'TTS-',
    reminderDaysBefore: 3,
  },
  attendance: {
    officeStart: '09:30',
    officeEnd: '18:00',
    staffLateAfterMin: 10,
    halfDayBelowHours: 4,
    fullDayHours: 8,
    studentLateAfterMin: 15,
    lowAttendanceAlertPct: 75,
    autoMarkAbsentAfter: '12:00',
  },
  permissions: [
    row('Dashboard', ['Full', 'Full', 'Full', 'Full', 'View']),
    row('Leads & Enquiries', ['Full', 'Full', 'None', 'Full', 'None']),
    row('Follow-ups', ['Full', 'Full', 'None', 'Full', 'None']),
    row('Admissions', ['Full', 'Full', 'None', 'View', 'None']),
    row('Students', ['Full', 'View', 'View', 'None', 'None']),
    row('Courses & Batches', ['Full', 'View', 'View', 'None', 'None']),
    row('Fee Collection', ['Full', 'Full', 'None', 'None', 'View']),
    row('Student Attendance', ['Full', 'None', 'Full', 'None', 'View']),
    row('Staff Attendance', ['Full', 'None', 'None', 'None', 'None']),
    row('Employees', ['Full', 'None', 'None', 'None', 'None']),
    row('Leave Management', ['Full', 'None', 'None', 'None', 'None']),
    row('Payroll', ['Full', 'None', 'None', 'None', 'None']),
    row('Mentor Reports', ['Full', 'None', 'Full', 'None', 'View']),
    row('Sales Calls', ['Full', 'None', 'None', 'Full', 'None']),
    row('Reports', ['Full', 'None', 'None', 'None', 'None']),
    row('Settings', ['Full', 'None', 'None', 'None', 'None']),
  ],
  notificationPrefs: [
    {
      event: 'Fee due reminder',
      description: 'Before an installment falls due',
      inApp: true,
      email: true,
      sms: true,
    },
    {
      event: 'Fee received',
      description: 'When a payment is recorded',
      inApp: true,
      email: true,
      sms: false,
    },
    {
      event: 'Follow-up due',
      description: "Morning digest of today's follow-ups",
      inApp: true,
      email: false,
      sms: false,
    },
    {
      event: 'Follow-up overdue',
      description: 'When a follow-up passes its due date',
      inApp: true,
      email: true,
      sms: false,
    },
    {
      event: 'New admission',
      description: 'When an admission is confirmed',
      inApp: true,
      email: true,
      sms: false,
    },
    {
      event: 'Leave request',
      description: 'When staff apply for leave',
      inApp: true,
      email: true,
      sms: false,
    },
    {
      event: 'Attendance alert',
      description: 'Low attendance or consecutive absences',
      inApp: true,
      email: false,
      sms: true,
    },
    {
      event: 'System updates',
      description: 'Product and maintenance notices',
      inApp: true,
      email: false,
      sms: false,
    },
  ],
};
