// Concatenates prisma/schema/**/*.prisma into prisma/schema.prisma.
// Edit files under prisma/schema/, never schema.prisma directly.
const fs = require('node:fs');
const path = require('node:path');

const schemaDir = path.join(__dirname, 'schema');
const outFile = path.join(__dirname, 'schema.prisma');

function collect(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name))
    .flatMap((entry) => {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) return collect(full);
      return entry.name.endsWith('.prisma') ? [full] : [];
    });
}

const files = [
  path.join(schemaDir, 'base.prisma'),
  ...collect(path.join(schemaDir, 'enums')),
  ...collect(path.join(schemaDir, 'models')),
];

const header = '// GENERATED by prisma/build-schema.js — DO NOT EDIT. Edit prisma/schema/ instead.\n';
const body = files
  .map((file) => {
    const name = path.relative(schemaDir, file).split(path.sep).join('/');
    return `// ---- ${name} ----\n${fs.readFileSync(file, 'utf8').trim()}\n`;
  })
  .join('\n');

fs.writeFileSync(outFile, `${header}\n${body}`);
console.log(`prisma/schema.prisma built from ${files.length} file(s)`);
