// Scans src/app for Lucide icon names and regenerates src/app/core/theme/icons.ts.
// Run: node scripts/generate-icons.mjs
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const appDir = join(root, 'src', 'app');
const typings = readFileSync(join(root, 'node_modules', '@lucide', 'angular', 'types', 'lucide-angular.d.ts'), 'utf8');
const exported = new Set(typings.match(/declare class (Lucide[A-Za-z0-9]+) extends LucideIconBase/g).map((m) => m.split(' ')[2]));

const toClass = (name) =>
  'Lucide' + name.split('-').map((p) => (/^\d/.test(p) ? p : p[0].toUpperCase() + p.slice(1))).join('');

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (full.endsWith('.ts') && !full.endsWith('icons.ts')) out.push(full);
  }
  return out;
}

const names = new Set();
const missing = new Set();
const patterns = [
  /(?:lucideIcon|icon|Icon|actionIcon)\s*[:=]\s*["'`]([a-z0-9-]+)["'`]/g,
  /\[lucideIcon\]="([^"]+)"/g,
];
for (const file of walk(appDir)) {
  const src = readFileSync(file, 'utf8');
  for (const re of patterns) {
    for (const m of src.matchAll(re)) {
      const chunk = m[1];
      const literals = chunk.includes("'") ? [...chunk.matchAll(/'([a-z0-9-]+)'/g)].map((x) => x[1]) : [chunk];
      for (const n of literals) {
        if (!/^[a-z0-9-]+$/.test(n)) continue;
        (exported.has(toClass(n)) ? names : missing).add(n);
      }
    }
  }
  // Values of *_ICONS maps: `Key: 'icon-name'`
  for (const block of src.matchAll(/ICONS[^=]*=\s*{([\s\S]*?)};/g)) {
    for (const m of block[1].matchAll(/'([a-z0-9-]+)'/g)) if (exported.has(toClass(m[1]))) names.add(m[1]);
  }
}

// Icons used only through dynamic bindings (keep in sync if you add more).
['circle', 'inbox', 'triangle-alert'].forEach((n) => names.add(n));

const sorted = [...names].sort();
const classes = sorted.map(toClass);
const out = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
import { EnvironmentProviders, Provider } from '@angular/core';
import {
${classes.map((c) => `  ${c},`).join('\n')}
  provideLucideConfig,
  provideLucideIcons,
} from '@lucide/angular';

/** Registers every icon used by name (\`<svg lucideIcon="name">\`). */
export function provideAppIcons(): (Provider | EnvironmentProviders)[] {
  return [
    provideLucideConfig({ size: 16, strokeWidth: 1.75 }),
    provideLucideIcons(
${classes.map((c) => `      ${c},`).join('\n')}
    ),
  ];
}
`;
writeFileSync(join(appDir, 'core', 'theme', 'icons.ts'), out);
console.log(`icons.ts: ${sorted.length} icons`);
if (missing.size) console.log('NOT FOUND in @lucide/angular:', [...missing].join(', '));
